import type {Metadata} from "next";
import {Nanum_Gothic} from "next/font/google";
import "./globals.css";

const nanum = Nanum_Gothic({
    weight: ['400', '700', '800'],
    subsets: ['latin'],
    variable: "--font-nanum-gothic",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${nanum.variable} antialiased`}
        >
        <h1 className="text-3xl font-bold text-red-600">
            안녕하세요.
        </h1>
        {children}
        </body>
        </html>
    );
}
