import type {Metadata} from "next";
import {Nanum_Gothic, Nanum_Gothic_Coding} from "next/font/google";
import "./globals.css";

const nanum = Nanum_Gothic({
    weight: ['400', '700', '800'],
    subsets: ['latin'],
    variable: "--font-nanum-gothic",
});

const nanumCoding = Nanum_Gothic_Coding({
    weight: ['400', '700'],
    subsets: ['latin'],
    variable: "--font-nanum-gothic-coding",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${nanum.variable} ${nanumCoding.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}